### ISSUE TITLE
容器中部署的应用服务偶尔因注册不上2.1.1版本的Nacos而启动失败（The application service deployed in the container occasionally fails to start due to unsuccessful registration with Nacos version 2.1.1）

### ISSUE THREAD

**Issue by zengyr49** [nacos-group/nacos-group.github.io#632]
我这边使用了2.1.1版本的Nacos。我这边应用服务使用的2.2.9.RELEASE版本的spring-cloud-starter-alibaba-nacos-discovery。应用服务部署在容器里面，此应用服务的启动大概有一半的概率会发生注册到Nacos失败而导致服务启动不成功。我检查过当时的网络，尝试过telnet，ping和查看监控都能够正常连接Nacos服务器，当时的Nacos的工作负载不高，应用服务也没有大量注册到Nacos，连接Nacos的超时时间设置了5秒钟默认（用不了5秒），没有网络隔离。而服务在本地启动复现，因此也没法debug定位问题。具体报错在附件，想烦请各位帮忙看看。摘出部分报错如下：
（I am using Nacos version 2.1.1. The application service uses version 2.2.9.RELEASE of spring-cloud-starter-alibaba-nacos-discovery. The application service is deployed in a container, and there is about a 50% chance that the service will fail to start due to a failure to register with Nacos. I have checked the network at the time, tried telnet, ping, and monitored the connection to the Nacos server, which were all normal. The workload of Nacos was not high at the time, and the application service did not have a large number of registrations with Nacos. The timeout for connecting to Nacos was set to a default of 5 seconds (which it didn't take up to 5 seconds), and there was no network isolation. The service cannot be reproduced when started locally, so it is impossible to debug and locate the problem. The specific error is in the attachment, I would like to ask you to help take a look. Here is a part of the error message）
[log_part.log](https://github.com/nacos-group/nacos-group.github.io/files/15057287/log_part.log)

[2024-04-19 09:48:07.681][ERROR][main][TID:N/A][][][o.s.boot.SpringApplication#reportFailure 837]LINECONTENT:Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)

	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)

	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)

	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.company.mcsb.salesleads.SalesleadsServiceApplicationStarter.main(SalesleadsServiceApplicationStarter.java:24)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.UndeclaredThrowableException: null

	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:82)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239)
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138)

	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)

	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 22 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288)

	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:128)

	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:114)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145)

	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
	... 35 common frames omitted

Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278)
	... 40 common frames omitted

**Comment by zengyr49** [comment]
看到其他人也遇到类似问题，我发邮件问过issue 9826的提出者tianqingzhao，他回复说换机子运行就没问题了。
我这边在容器中部署，并且以低内存（尤其是-Xms设置很小的时候）运行，能够完美复现。而增大资源则服务启动速度更快了，同时也不会再出现类似的错误。综上，我推测是spring boot服务启动过程中，nacos注册的线程，在发起注册后因内存不足，调度的时候挂起了。等到重新唤醒后，等待返回结果的时候就超时了。
Seeing that others have also encountered similar issues, I emailed the proposer of issue 9826, Tianqingzhao, who replied that the problem was resolved when running on a different machine. On my end, deploying in a container and running with low memory (especially when -Xms is set to a very small value) can perfectly reproduce the issue. However, increasing the resources makes the service start faster and similar errors no longer occur. In conclusion, I suspect that during the startup process of the Spring Boot service, the thread registered by Nacos is suspended when scheduling after initiating the registration due to insufficient memory. When it is awakened again and waiting for the return result, it times out.
